name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: print hello
        run: |
          echo "Hello world"
          echo "This is Akhila"
      - name: print bye
        run: echo "Good - Bye!"
